# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiptrader', '0003_listing_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='starship',
            options={'ordering': ['-id']},
        ),
    ]
